/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AdminSearchProductsRequestDTOSortDirection } from './adminSearchProductsRequestDTOSortDirection';
import type { AdminSearchProductsRequestDTOSortField } from './adminSearchProductsRequestDTOSortField';

export interface AdminSearchProductsRequestDTO {
  /** @minimum 0 */
  page?: number;
  /**
   * @minimum 20
   * @maximum 100
   */
  sizePerPage?: number;
  sortDirection?: AdminSearchProductsRequestDTOSortDirection;
  sortField?: AdminSearchProductsRequestDTOSortField;
}
