/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type AdminSearchProductsRequestDTOSortDirection = typeof AdminSearchProductsRequestDTOSortDirection[keyof typeof AdminSearchProductsRequestDTOSortDirection];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminSearchProductsRequestDTOSortDirection = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const;
