/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { MoneyDTO } from './moneyDTO';

export interface AdminCreateProductRequestDTO {
  /**
   * @minLength 3
   * @maxLength 50
   */
  name: string;
  previewImageURL: string;
  unitPrice: MoneyDTO;
}
