/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type AdminSearchProductsRequestDTOSortField = typeof AdminSearchProductsRequestDTOSortField[keyof typeof AdminSearchProductsRequestDTOSortField];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminSearchProductsRequestDTOSortField = {
  ID: 'ID',
  NAME: 'NAME',
  PHONE_NUMBER: 'PHONE_NUMBER',
} as const;
