/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ProductForAdminDTO } from './productForAdminDTO';

export interface PageDTOProductForAdminDTO {
  content?: ProductForAdminDTO[];
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  totalElements?: number;
  totalPages?: number;
}
