/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AdminSearchProductsRequestDTO } from './adminSearchProductsRequestDTO';

export type SearchParams = {
request: AdminSearchProductsRequestDTO;
};
