/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ScopedRoleDTO } from './scopedRoleDTO';

export interface UserForAdminDTO {
  id?: string;
  roles?: ScopedRoleDTO[];
  username?: string;
}
