/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AdminSearchProductsRequestDTOSortDirection } from "../dtos/adminSearchProductsRequestDTOSortDirection";
import type { AdminSearchProductsRequestDTOSortField } from "../dtos/adminSearchProductsRequestDTOSortField";

export type AdminSearchProductsRequestDTO = {
  /** @minimum 0 */
  page?: number;
  /**
   * @minimum 20
   * @maximum 100
   */
  sizePerPage?: number;
  sortDirection?: keyof AdminSearchProductsRequestDTOSortDirection & "string";
  sortField?: keyof AdminSearchProductsRequestDTOSortField & "string";
} & { [key: string]: string | number };
